FROM hashicorp/terraform:1.5.4

# Python used in the gitlab runner code to get dependencies so ensure the image has pip
RUN apk --no-cache add \
        ca-certificates \
        python3 \
        py3-pip

## add the git config to prevent /usr/bin/git exited with 128: fatal: detected dubious ownership in repository at ...
RUN git config --global --add safe.directory "*"
